import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { COMPONENT_NAMES, components } from "../dist/register/components.js";
import { accepts } from "../dist/register/describe.js";

/**
 * Writes the language reference.
 *
 * The components come from the register, so a component added there appears
 * here with nothing else edited, and the sentence saying what a parameter takes
 * is the same one the validator uses when it refuses a value. A reference
 * promising something the parser refuses is worse than none, and writing it by
 * hand is how that happens.
 *
 * The prose around the components is written by hand, because the four grammar
 * rules and the list of what the language deliberately lacks are arguments
 * rather than data.
 *
 * Reads the built package rather than the source, so it runs after `tsc` in the
 * package's build.
 */

const here = dirname(fileURLToPath(import.meta.url));
const REFERENCE = join(here, "..", "reference");
const OUTPUT = join(here, "..", "..", "..", "docs", "content-language.md");

/** What a body rule means for somebody writing one. */
const BODY = {
  required: "Needs a body.",
  optional: "May take a body.",
  never: "Takes no body.",
};

/** A default, shown as it is written in a document. */
function written(value) {
  return `\`${value}\``;
}

/** A table cell, with the one character that would end it early escaped. */
function cell(text) {
  return String(text).replaceAll("|", "\\|");
}

/** The parameters of one component, as a table. */
function parameterTable(definition) {
  const names = Object.keys(definition.parameters);
  if (names.length === 0) return ["It takes no parameters."];

  const rows = names.map((name) => {
    const parameter = definition.parameters[name];
    const label = parameter.required ? `\`${name}\` (required)` : `\`${name}\``;
    const fallback = parameter.default === undefined ? "" : written(parameter.default);
    return `| ${label} | ${cell(parameter.description)} | ${cell(accepts(parameter))} | ${fallback} |`;
  });

  const lines = ["| Parameter | What it is for | Takes | Default |", "| --- | --- | --- | --- |", ...rows];

  if (definition.unnamed) {
    lines.push("", `\`${definition.unnamed}\` may be written first without its name.`);
  }

  return lines;
}

/** One component, as a section. */
function section(name) {
  const definition = components[name];

  return [
    `### ${name}`,
    "",
    definition.description,
    "",
    `${BODY[definition.body]} Rendered by \`${definition.renders}\`.`,
    "",
    ...parameterTable(definition),
    "",
    "```",
    definition.example,
    "```",
  ].join("\n");
}

const introduction = await readFile(join(REFERENCE, "introduction.md"), "utf8");
const absent = await readFile(join(REFERENCE, "deliberately-absent.md"), "utf8");

const document = [
  "<!-- Generated by packages/content/scripts/reference.mjs. Do not edit by hand. -->",
  "<!-- The prose comes from packages/content/reference/, the components from the register. -->",
  "",
  "# The content language",
  "",
  introduction.trim(),
  "",
  "## The components",
  "",
  `There are ${COMPONENT_NAMES.length} of them, and this list is generated from the register, so it is what the parser actually accepts.`,
  "",
  COMPONENT_NAMES.map(section).join("\n\n"),
  "",
  "## What the language deliberately lacks",
  "",
  absent.trim(),
  "",
].join("\n");

await writeFile(OUTPUT, document, "utf8");
console.log(`${OUTPUT}: ${COMPONENT_NAMES.length} components`);
