import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { COMPONENT_NAMES } from "./register/components.js";
import { validateContent } from "./validate/validate.js";

/**
 * What has to hold of the published reference.
 *
 * A reference that promises something the parser refuses is worse than none,
 * because the reader follows it and loses the time twice. So every example in
 * it is parsed and validated here, the hand-written ones at the top as well as
 * the generated ones, and every component the register declares has to have a
 * section.
 *
 * Whether the file is current is a separate question, and the gate answers it:
 * the build regenerates it and `git diff --exit-code` refuses a stale copy.
 */

/** The published reference, read from where the build writes it. */
const REFERENCE = readFileSync(
  fileURLToPath(new URL("../../../docs/content-language.md", import.meta.url)),
  "utf8",
);

/**
 * Every example in the document.
 *
 * Untagged fences only. A fence carrying a language is showing something else,
 * such as the JSON a renderer receives, and running it through this parser
 * would fail for a reason that says nothing about the language.
 */
function examplesIn(markdown: string): string[] {
  return [...markdown.matchAll(/^```\n([\s\S]*?)^```$/gm)].map((match) => match[1] ?? "");
}

const EXAMPLES = examplesIn(REFERENCE);

describe("the reference", () => {
  it("is not empty", () => {
    expect(REFERENCE.length).toBeGreaterThan(0);
  });

  it("says it is generated, so nobody edits it by hand", () => {
    expect(REFERENCE.startsWith("<!-- Generated by")).toBe(true);
  });

  it.each(COMPONENT_NAMES)("has a section for %s", (name) => {
    expect(REFERENCE).toContain(`### ${name}\n`);
  });

  it("holds at least one example per component", () => {
    expect(EXAMPLES.length).toBeGreaterThanOrEqual(COMPONENT_NAMES.length);
  });

  it.each(EXAMPLES)("example %# is something the validator accepts", (example) => {
    const { findings } = validateContent(example);

    expect(findings.map((finding) => finding.message)).toEqual([]);
  });
});
