import { sql } from "drizzle-orm";
import { timestamp, uuid } from "drizzle-orm/pg-core";

/**
 * Column shapes that every table here shares.
 *
 * One definition rather than one per file, because a key that is generated
 * differently in one table is a difference nothing announces.
 */

/**
 * The primary key every table uses.
 *
 * `uuidv7` is generated by Postgres itself from version 18, so a row does not
 * have to be given a key before it is written. It is time-ordered, which keeps
 * rows written together in the same part of the index, and it carries 74
 * random bits, which is far past guessing for anything reached by its
 * identifier rather than by its path.
 */
export const identifier = () => uuid().primaryKey().default(sql`uuidv7()`);

/**
 * A point in time that is always set, defaulting to the moment the row is
 * written.
 *
 * Every timestamp in this schema carries its zone, because a site written in
 * Bregenz and served from Prague has two of them and a naive timestamp silently
 * picks one. Timestamps that may be absent, such as when something was
 * published or revoked, are declared where they are used, since their being
 * null is the thing they are for.
 *
 * @param name - The column name in the database.
 */
export const instant = (name: string) => timestamp(name, { withTimezone: true }).notNull().defaultNow();
