// Reads the stylesheets and writes the few values TypeScript needs.
//
// The stylesheets are the source. Anything here that were typed out a second
// time would be a second answer to a question `scale.css` already answers, and
// the two would drift the first time a step was added: nothing would fail, and
// a component would simply accept a value the stylesheet has no property for.
//
// The result is committed, so a type check and a test suite work without a
// build having run. The gate runs this and then refuses a dirty tree, which is
// what makes a stale copy a failure rather than a surprise.
import { readFile, writeFile } from "node:fs/promises";

const target = new URL("../src/generated/scales.ts", import.meta.url);

const css = await readFile(new URL("../src/scale.css", import.meta.url), "utf8");
const palette = await readFile(new URL("../src/palettes.css", import.meta.url), "utf8");

/**
 * Every declared step of one series, in the order the stylesheet declares them.
 *
 * Matches a declaration rather than any occurrence, so a `var(--space-3)` used
 * further down does not read as a step of its own.
 */
function steps(text, prefix) {
  const declaration = new RegExp(`^\\s*--${prefix}-([0-9a-z]+)\\s*:`, "gm");
  return [...text.matchAll(declaration)].map((match) => match[1]);
}

const space = steps(css, "space");
if (space.length === 0) throw new Error("scale.css declares no --space-N properties");

const tones = steps(palette, "state");
if (tones.length === 0) throw new Error("palettes.css declares no --state-* properties");

const generated = `// Generated by packages/tokens/scripts/derive.mjs from scale.css.
// Run \`pnpm --filter @layered/tokens build\` after changing a scale.

/**
 * The steps of the space scale, as they are declared in \`scale.css\`.
 *
 * Read by anything that has to offer a choice of spacing rather than a number:
 * the content language's register says \`spacing\` takes one of these, and a step
 * added to the stylesheet appears there with nothing else edited.
 *
 * The values are deliberately absent. What a step is worth in pixels is the
 * stylesheet's business, and a component that knew it would be a component
 * that could be wrong about it.
 */
export const SPACE_STEPS = [${space.map((step) => `"${step}"`).join(", ")}] as const;

/** One step of the space scale. */
export type SpaceStep = (typeof SPACE_STEPS)[number];

/** What a step is called as a custom property, which is the only form anything should use. */
export function spaceToken(step: SpaceStep): string {
  return \`var(--space-\${step})\`;
}

/**
 * The status colours, as they are declared in \`palettes.css\`.
 *
 * What a component means when it says a thing went well, is worth knowing, is
 * worth care, or has gone wrong. The content language's \`Note\` offers exactly
 * these, so adding a fifth to the palette offers it to authors with nothing
 * else edited.
 *
 * The accent is not among them on purpose: it is the site's own colour rather
 * than a statement about something, and a status that shared its hue would read
 * as the accent wherever the two met.
 */
export const STATUS_TONES = [${tones.map((tone) => `"${tone}"`).join(", ")}] as const;

/** One status tone. */
export type StatusTone = (typeof STATUS_TONES)[number];
`;

await writeFile(target, generated);
console.log(
  `tokens: derived ${space.length} space steps and ${tones.length} status tones into src/generated/scales.ts`,
);
