// Generated by extract.py from the Publii database. Do not edit by hand.
export const content = {
  "entries": [
    {
      "id": 32,
      "title": "NeXTSTEP Naming",
      "slug": "nextstep-naming",
      "kind": "post",
      "status": "public",
      "featured": false,
      "language": "en",
      "translationOf": null,
      "date": 1765132069009,
      "readTime": 2,
      "excerpt": "For decades, the precise naming and capitalization of NeXT’s operating systems have been a source of endless confusion. Was it NeXTstep, NeXTStep, or NEXTSTEP? The answer often changed…",
      "paragraphs": [
        "For decades, the precise naming and capitalization of NeXT’s operating systems have been a source of endless confusion. Was it NeXTstep, NeXTStep, or NEXTSTEP? The answer often changed depending on the specific version, the architecture, or the marketing strategy of the time.",
        "Even today, these terms are frequently mixed up in discussions about Apple's history. To finally bring some clarity to this historical mix-up, the following table breaks down the correct spelling and usage for each iteration, distinguishing clearly between the Operating System and the API."
      ],
      "headings": [],
      "tags": [
        {
          "name": "BSD",
          "slug": "bsd"
        },
        {
          "name": "NeXT",
          "slug": "next"
        },
        {
          "name": "NeXTSTEP",
          "slug": "nextstep"
        },
        {
          "name": "Operating System",
          "slug": "operating-system"
        }
      ],
      "image": "../assets/img/banner_NeXT_naming.jpg"
    },
    {
      "id": 30,
      "title": "AI Operating Guide",
      "slug": "ai-operating-guide",
      "kind": "post",
      "status": "public",
      "featured": false,
      "language": "en",
      "translationOf": null,
      "date": 1764543931821,
      "readTime": 3,
      "excerpt": "This guide describes the key strategies and rules for achieving consistent, traceable, and precise responses when interacting with an AI. It serves as a personal rulebook designed to keep…",
      "paragraphs": [
        "This guide describes the key strategies and rules for achieving consistent, traceable, and precise responses when interacting with an AI. It serves as a personal rulebook designed to keep context stable, minimize hallucinations, and ensure efficient collaboration.",
        "text Here are the fixed parameters for the entire chat: 1. The hardware does not change. 2. The goal is a modular design. 3. No assumptions without my instruction.",
        "text Your task is strictly to analyze my text. No additions, no assumptions, no reformulations.",
        "text Step 1: List all requirements. Step 2: Confirm them. Step 3: Then create the solution. Begin with Step 1.",
        "Example: text If information is missing, ask first. Never guess or fill gaps.",
        "text Here is the new, binding context for the rest of the chat: (…) Use this section exclusively as the basis.",
        "text We will use the following terms consistently: - \"Module\" instead of \"Component\" - \"Frame\" instead of \"Housing Unit\" Please maintain terminological stability."
      ],
      "headings": [
        "1. Rules for Maintaining Context Stability (Anti‑Hallucination)",
        "1.1 Establish Fixed Reference Points",
        "1.2 Clearly Limit the Task",
        "1.3 Step‑by‑Step Workflow"
      ],
      "tags": [],
      "image": "../assets/img/banner-ai-operation-guide.jpg"
    },
    {
      "id": 29,
      "title": "KI Bedienungsanleitung",
      "slug": "ki-bedienungsanleitung",
      "kind": "post",
      "status": "hidden",
      "featured": false,
      "language": "de",
      "translationOf": 30,
      "date": 1764543609439,
      "readTime": 3,
      "excerpt": "Diese Anleitung beschreibt die wichtigsten Strategien und Regeln, um in Chats mit einer KI konsistente, nachvollziehbare und präzise Antworten zu erhalten. Sie dient als persönliches…",
      "paragraphs": [
        "Diese Anleitung beschreibt die wichtigsten Strategien und Regeln, um in Chats mit einer KI konsistente, nachvollziehbare und präzise Antworten zu erhalten. Sie dient als persönliches Regelwerk, das den Kontext stabil hält, Halluzinationen minimiert und effiziente Zusammenarbeit ermöglicht.",
        "text Hier sind die fixen Rahmenbedingungen für den gesamten Chat: 1. Die Hardware bleibt unverändert. 2. Ziel ist ein modularer Aufbau. 3. Keine Annahmen ohne meine Vorgabe.",
        "text Deine Aufgabe ist ausschließlich, meinen Text zu analysieren. Keine Ergänzungen, keine Annahmen, keine Umformulierungen.",
        "text Schritt 1: Liste alle Anforderungen auf. Schritt 2: Bestätige sie. Schritt 3: Erstelle dann die Lösung. Beginne mit Schritt 1.",
        "text Nutze Version B aus weiter oben und ändere nur Punkt 2 und Punkt 4.",
        "text Wenn eine Information fehlt, frag zuerst nach. Niemals raten oder ergänzen.",
        "text Hier ist der neue, verbindliche Kontext für den Rest des Chats: (…) Nutze ausschließlich diesen Abschnitt als Grundlage."
      ],
      "headings": [
        "1. Regeln zur Kontext-Stabilisierung (Anti-Halluzination)",
        "1.1 Fixpunkte setzen",
        "1.2 Aufgaben klar begrenzen",
        "1.3 Schrittweise Vorgehensweise"
      ],
      "tags": [],
      "image": "../assets/img/banner-ai-operation-guide-2.jpg"
    },
    {
      "id": 26,
      "title": "Editor Cheat-Sheets (for Mac Keyboards)",
      "slug": "editor-cheat-sheets",
      "kind": "post",
      "status": "public",
      "featured": false,
      "language": "en",
      "translationOf": null,
      "date": 1756596416155,
      "readTime": 3,
      "excerpt": "I really enjoy using the console. Not only on my Mac, but also frequently on remote systems. And here I constantly switch between the editors vi and nano . Unfortunately, I am also a very…",
      "paragraphs": [
        "I really enjoy using the console. Not only on my Mac, but also frequently on remote systems. And here I constantly switch between the editors vi and nano . Unfortunately, I am also a very forgetful person and keep forgetting the same keyboard shortcuts or mixing them up. So what could be more obvious than creating little cheat sheets of the most frequently used shortcuts as a reminder? Here we go..."
      ],
      "headings": [
        "Cheat Sheet: nano",
        "Cheat Sheet: vi"
      ],
      "tags": [
        {
          "name": "Editor",
          "slug": "editor"
        },
        {
          "name": "Linux",
          "slug": "linux"
        },
        {
          "name": "nano",
          "slug": "nano"
        },
        {
          "name": "vi",
          "slug": "vi"
        },
        {
          "name": "Text Editor",
          "slug": "text-editor"
        }
      ],
      "image": "../assets/img/banner-texteditors.jpg"
    },
    {
      "id": 25,
      "title": "External Activity and Power LEDs on RPi 5",
      "slug": "rpi5-with-external-leds",
      "kind": "post",
      "status": "public",
      "featured": false,
      "language": "en",
      "translationOf": null,
      "date": 1756581902943,
      "readTime": 4,
      "excerpt": "On the Raspberry Pi 5, the former green activity LED and red power LED are combined into a single multi-function LED. It is no longer wired directly to simple GPIO pins. If you want to…",
      "paragraphs": [
        "On the Raspberry Pi 5, the former green activity LED and red power LED are combined into a single multi-function LED. It is no longer wired directly to simple GPIO pins. If you want to relocate this LED to an external housing or add your own indicators, you must assign free GPIO pins and configure the operating system to drive them with the desired functions.",
        "This document describes how to connect and configure one LED as an activity indicator and another LED as a power indicator to freely selectable GPIO pins.",
        "The instructions are based on Raspberry Pi OS (Debian Bookworm) and work with the Raspberry Pi 5.",
        "- Raspberry Pi 5 with the latest Raspberry Pi OS (Bookworm). - Two LEDs (e.g., 5 mm or 3 mm) and suitable series resistors (47–330 Ω). - Two free GPIO pins on the 40-pin header (e.g., GPIO 23 for the activity LED and GPIO 17 for the power LED). - Connection cable or breadboard.",
        "1. Activity‑LED (grün): - GPIO 23 (pin 16) → LED anode → series resistor → LED. - LED cathode → GND (e.g., pin 6).",
        "2. Power‑LED (rot): - GPIO 17 (pin 11) → LED anode → series resistor → LED. - LED cathode → GND.",
        "Note: The LEDs must not draw more than 16mA per pin. With the resistors mentioned, you are on the safe side."
      ],
      "headings": [
        "Introduction",
        "Hardware requirements",
        "Wiring",
        "Update system"
      ],
      "tags": [
        {
          "name": "RaspberryPi",
          "slug": "raspberrypi"
        },
        {
          "name": "Software",
          "slug": "software"
        }
      ],
      "image": "../assets/img/banner-rpi5-external-leds-2.jpg"
    },
    {
      "id": 24,
      "title": "NeXTSTEP: On a RPi 5",
      "slug": "nextstep-on-rpi5-en",
      "kind": "post",
      "status": "public",
      "featured": false,
      "language": "en",
      "translationOf": null,
      "date": 1755877218945,
      "readTime": 9,
      "excerpt": "In this guide, I'll show you step-by-step how to install NeXTSTEP 3.3 on a Raspberry Pi 5 using the Previous emulator. This guide is based on Raspberry Pi OS Lite to create a minimal system…",
      "paragraphs": [
        "In this guide, I'll show you step-by-step how to install NeXTSTEP 3.3 on a Raspberry Pi 5 using the Previous emulator. This guide is based on Raspberry Pi OS Lite to create a minimal system that boots directly into the NeXTSTEP interface after startup.",
        "Raspberry Pi 5  A fast SD card or USB drive (at least 32 GB recommended). An SSD will offer better performance but is not required.  A suitable power supply for your Raspberry Pi 5 (5V/5A)  Keyboard, mouse, and monitor  A computer with an SD card reader or USB port",
        "Raspberry Pi Imager  Raspberry Pi OS Lite (64-bit)  NeXTSTEP installation files Since I am only focusing on setting up NeXTSTEP for a Cube, we only need the ISO image of the User Installation. We do not need a boot floppy image for this machine.",
        "NeXTSTEP is often considered \"abandonware\" because it is no longer commercially available and is no longer maintained by the original manufacturer. An excellent and comprehensive source for all necessary images and other useful software is the archive at nextcomputers.org or the Internet Archive.",
        "The NeXT ROM files are not needed, as they are supplied with the installation of Previous. Should you still wish to download them, you can find a bundle of different files for various models at macintoshrepository.org.",
        "Insert the SD card or connect the USB drive to your computer and start the Raspberry Pi Imager. I'll skip a detailed explanation of how to use the Raspberry Pi Imager at this point and assume you are familiar with it.",
        "Once the flashing is complete, you can boot your Raspberry Pi with this SD card / USB drive."
      ],
      "headings": [
        "Prerequisites",
        "Hardware",
        "Software",
        "Where can I find NeXTSTEP files?"
      ],
      "tags": [],
      "image": "../assets/img/banner-nextstep33-2.jpg"
    },
    {
      "id": 23,
      "title": "NeXTSTEP: Auf einem RPi 5",
      "slug": "nextstep-on-rpi5-de",
      "kind": "post",
      "status": "hidden",
      "featured": false,
      "language": "de",
      "translationOf": 24,
      "date": 1755863014239,
      "readTime": 9,
      "excerpt": "In dieser Anleitung zeige ich dir Schritt für Schritt, wie du NeXTSTEP 3.3 mithilfe des Emulators Previous auf einem Raspberry Pi 5 installierst. Diese Anleitung basiert auf Raspberry Pi OS…",
      "paragraphs": [
        "In dieser Anleitung zeige ich dir Schritt für Schritt, wie du NeXTSTEP 3.3 mithilfe des Emulators Previous auf einem Raspberry Pi 5 installierst. Diese Anleitung basiert auf Raspberry Pi OS Lite, um ein minimales System zu schaffen, das nach dem Hochfahren direkt in die NeXTSTEP-Oberfläche startet.",
        "Raspberry Pi 5  Eine schnelle SD-Karte oder ein USB-Stick (mindestens 32 GB empfohlen). Eine SSD bietet eine bessere Leistung, ist aber nicht erforderlich.  Ein passendes Netzteil für deinen Raspberry Pi 5 (5V/5A)  Tastatur, Maus und Monitor  Ein Computer mit einem SD-Kartenleser oder USB-Anschluss",
        "Raspberry Pi Imager  Raspberry Pi OS Lite (64-Bit)  NeXTSTEP-Installationsdateien \\ Da ich mich hier nur auf das Einrichten von NeXTSTEP für einen Cube konzentriere, benötigen wir auch nur das ISO Image der User Installation. Ein Boot-Disketten-Image benötigen wir für diese Maschine nicht.",
        "NeXTSTEP wird oft als so genannte \"Abandonware\" betrachtet, da es kommerziell nicht mehr verfügbar ist und vom ursprünglichen Hersteller nicht mehr gepflegt wird. Eine exzellente und umfassende Quelle für alle benötigten Images und weitere nützliche Software ist das Archiv auf nextcomputers.org oder das Internet Archive.",
        "Die NeXT ROM-Files werden nicht benötigt, da diese durch die Installation von Previous mitgeliefert werden. Solltest du sie dennoch herunterladen wollen, dann findest du ein Bundle verschiedener Files für verschiedene Modelle im macintoshrepository.org.",
        "Stecke die SD-Karte ein oder verbinde den USB-Stick mit deinem Computer und starte den Raspberry Pi Imager. Ich verzichte an dieser Stelle auf eine ausführlich Erklärung, wie man mit Raspberry Pi Imager arbeitet, und setze das einfach mal voraus.",
        "Wenn das Flaschen erledigt ist, kannst du deinen Raspberry Pi mit dieser SD-Karte / diesem USB-Stick booten."
      ],
      "headings": [
        "Voraussetzungen",
        "Hardware",
        "Software",
        "Wo finde ich NeXTSTEP-Dateien?"
      ],
      "tags": [
        {
          "name": "Emulator",
          "slug": "emulator"
        },
        {
          "name": "NeXT",
          "slug": "next"
        },
        {
          "name": "NeXTSTEP",
          "slug": "nextstep"
        },
        {
          "name": "Previous",
          "slug": "previous"
        },
        {
          "name": "RaspberryPi",
          "slug": "raspberrypi"
        }
      ],
      "image": "../assets/img/banner-nextstep33.jpg"
    },
    {
      "id": 22,
      "title": "Website Design: Die Zweite",
      "slug": "website-design-die-zweite",
      "kind": "post",
      "status": "public",
      "featured": false,
      "language": "de",
      "translationOf": null,
      "date": 1754607575873,
      "readTime": 4,
      "excerpt": "Vor ein paar Tagen habe ich begonnen, meine Website neu zu gestalten. Da ich dafür die großartige Software Publii verwende, bedeutet das in der Praxis, dass ich ein neues Theme installiere…",
      "paragraphs": [
        "Vor ein paar Tagen habe ich begonnen, meine Website neu zu gestalten. Da ich dafür die großartige Software Publii verwende, bedeutet das in der Praxis, dass ich ein neues Theme installiere sowie benutzerdefinierten CSS- und Javascript-Code schreibe. Letztendlich blieb es aber nicht nur dabei, sondern ich musste auch einige der Theme-Templates selbst bearbeiten.",
        "Das klingt zunächst einmal ziemlich einfach. Aber nur auf den ersten Blick! Ich bin seit 30 Jahren Softwareentwickler, aber eben hauptsächlich für macOS und iOS. Ich kann Objective-C, Swift und SwiftUI recht gut, aber wenn es um Webentwicklung geht, bin ich ein echter Noob!",
        "Also beschloss ich, etwas auszuprobieren, was ich noch nie zuvor versucht hatte. Ich griff zum nächstbesten LLM – genauer gesagt ClaudeAI – und schrieb ihm, worum es ging. Dann zeigte ich ihm ein paar Screenshots vom aktuellen Stand der Website mit dem neuen Theme und dessen main.css und erklärte ihm, was ich wollte und wie ich es wollte. Alles in kleinen Häppchen, damit der Prompt nicht zu komplex wurde.",
        "Und zu meiner Überraschung hat das wirklich sehr gut funktioniert. Oft habe ich aber auch selbst Hand angelegt. Ich hab mir die Developer-Tools des Browser geöffnet, bin die ganzen Tags durchgegangen und hab so lange dran herum geschraubt, bis es passte. Dann hab ich von den Stellen in den Developer-Tools des Browser grossflächig einen Screenshot erstellt, diesen in den ClaudeAI Chat gekübelt und gesagt: \"Gib mir den CSS Code aus dem Bild.\" Diesen habe ich dann einfach an den Custom CSS Code in Publii angehängt. Wenn ein Part aus meiner Sicht optisch soweit fertig war, hab ich den ganzen CSS Code wieder aus Publii kopiert, und ihn mit einem Prompt ClaudeAI vor die Füße geworfen:",
        "Joa, und das hat es dann auch gemacht. Und zwar sehr gut sogar! Claude hat mir sehr genau beschrieben, was es gemacht hat und warum. Es hat mir den Code dokumentiert und auch hier an manchen Stellen als Kommentar hinten dran geschrieben, warum es diesen Code gibt und was er macht. Das hat mir gefallen.",
        "Das Einzige was an Claude wirklich nervt ist, dass man sehr schnell an sein \"Nutzungslimit\" kommt. Und das obwohl ich einen \"Pro-Plan\" nutze, der mich immerhin um die 20 Euro pro Monat kostet! So passiert es immer wieder dass er eine Anfrage fertig bearbeitet, und dann mittendrin einfach aufhört, weil... ja eben weil Nutzungslimit und so. 😤",
        "Dieser Umstand hat mich dazu gebracht, zwischendurch mal die Fronten zu wechseln, und Google Gemini auszuprobieren. Das ist in Sachen Programmieren ähnlich gut wie Claude mit dem Model \"Opus 4.0\" , aber hat ein wesentlich größer ausgelegtes Limit! Es kommt mir in der Code-Generierung/-Ausgabe auch etwas schneller vor als Claude."
      ],
      "headings": [
        "Sag niemals \"Nie\" zu KI",
        "3D Viewer",
        "Fazit"
      ],
      "tags": [
        {
          "name": "CSS",
          "slug": "css"
        },
        {
          "name": "Javascript",
          "slug": "javascript"
        },
        {
          "name": "Software",
          "slug": "software"
        },
        {
          "name": "Web-Development",
          "slug": "web-development"
        }
      ],
      "image": "../assets/img/banner-website-design.jpg"
    },
    {
      "id": 12,
      "title": "ono: The Raspberry Pi Case",
      "slug": "ono",
      "kind": "page",
      "status": "draft",
      "featured": false,
      "language": "en",
      "translationOf": null,
      "date": 1754175705071,
      "readTime": 1,
      "excerpt": "[{\"id\":\"cac14783-500c-46f3-a65b-20c1ee3b2730\",\"type\":\"publii-paragraph\",\"content\":\"\",\"config\":{\"textAlign\":\"left\",\"advanced\":{\"style\":\"\",\"cssClasses\":\"\",\"id\":\"\"}}}]",
      "paragraphs": [],
      "headings": [],
      "tags": [],
      "image": null
    },
    {
      "id": 11,
      "title": "NeXT MegaPixel Display mini",
      "slug": "next-megapixel",
      "kind": "page",
      "status": "draft",
      "featured": false,
      "language": "en",
      "translationOf": null,
      "date": 1754175527910,
      "readTime": 1,
      "excerpt": "[{\"id\":\"e9cac673-2a7f-4b64-a50d-cc2d5e1c1297\",\"type\":\"publii-paragraph\",\"content\":\"\",\"config\":{\"textAlign\":\"left\",\"advanced\":{\"style\":\"\",\"cssClasses\":\"\",\"id\":\"\"}}}]",
      "paragraphs": [],
      "headings": [],
      "tags": [],
      "image": null
    },
    {
      "id": 9,
      "title": "NeXTcube mini",
      "slug": "cube",
      "kind": "page",
      "status": "draft",
      "featured": false,
      "language": "en",
      "translationOf": null,
      "date": 1754170693835,
      "readTime": 1,
      "excerpt": "[{\"id\":\"b9503109-d0c5-4c3a-b91b-2e59e1bb38cb\",\"type\":\"publii-paragraph\",\"content\":\"\",\"config\":{\"textAlign\":\"left\",\"advanced\":{\"style\":\"\",\"cssClasses\":\"\",\"id\":\"\"}}}]",
      "paragraphs": [],
      "headings": [],
      "tags": [],
      "image": null
    },
    {
      "id": 8,
      "title": "Projects",
      "slug": "projects",
      "kind": "page",
      "status": "public",
      "featured": false,
      "language": "en",
      "translationOf": null,
      "date": 1754170248194,
      "readTime": 1,
      "excerpt": "Random selection of some of my projects. The topics range from woodworking and 3D printing to some electronics.",
      "paragraphs": [
        "Random selection of some of my projects. The topics range from woodworking and 3D printing to some electronics."
      ],
      "headings": [],
      "tags": [],
      "image": "../assets/img/banner_projects-2.jpg"
    },
    {
      "id": 7,
      "title": "NeXT: SoundBox mini",
      "slug": "next-soundbox",
      "kind": "page",
      "status": "public",
      "featured": false,
      "language": "en",
      "translationOf": null,
      "date": 1754147903283,
      "readTime": 5,
      "excerpt": "Interactive technical showcase of the NeXT SoundBox mini, presenting 3D model visualization, complete circuit schematics, and detailed component documentation with full Bill of Materials…",
      "paragraphs": [
        "Interactive technical showcase of the NeXT SoundBox mini, presenting 3D model visualization, complete circuit schematics, and detailed component documentation with full Bill of Materials and part specifications.",
        "This is a replica of the NeXT SoundBox on a scale of 1:2 with a custom USB-Audio controller board, which drives a mono speaker. The circuit converts digital audio data from the USB port into an analog signal, amplifies it, and outputs it to a speaker. The following diagram shows the path from data to sound.",
        "This part of the circuit is the interface to the outside world. It receives power and data from the USB port, filters the voltage, and protects the entire circuit from electrostatic discharge.",
        "The PCM2706PJT is a USB audio codec that integrates a complete stereo digital-to-analog converter (DAC) with USB interface functionality on a single chip. It appears as a standard USB audio device to any host computer, requiring no custom drivers, and converts digital audio data received over USB into high-quality analog stereo output signals. The chip includes an integrated USB transceiver, digital audio processing, and stereo DAC with built-in headphone amplifier, supporting sample rates up to 48kHz at 16-bit resolution.",
        "This simple passive circuit combines the left and right audio channels from the DAC into a single mono signal and prepares it for the mono amplifier.",
        "The PAM8302A is a Class-D mono audio amplifier integrated circuit that converts low-level audio signals into amplified output capable of driving small speakers directly. It delivers up to 2.5W of power into a 4Ω speaker while maintaining high efficiency of up to 90%, making it ideal for battery-powered portable devices. The chip features built-in thermal and overcurrent protection, requires minimal external components, and operates from a single 2.5V to 5.5V supply."
      ],
      "headings": [
        "Functional Overview",
        "Component Blocks in Detail",
        "USB Input",
        "USB DAC (PCM2706PJT)"
      ],
      "tags": [],
      "image": "../assets/img/FeatureImage-NeXTSoundBox.jpg"
    },
    {
      "id": 17,
      "title": "NeXT mini Replica Interest",
      "slug": "next-mini-replica-interest",
      "kind": "post",
      "status": "public",
      "featured": true,
      "language": "en",
      "translationOf": null,
      "date": 1733933700000,
      "readTime": 3,
      "excerpt": "This project is a labor of love that I've been working on for a very long time. Not continuously, but every now and then, as my free time allowed. At some point, I published a few…",
      "paragraphs": [
        "This project is a labor of love that I've been working on for a very long time. Not continuously, but every now and then, as my free time allowed. At some point, I published a few screenshots (this is the very first version ) of my 3D model and immediately received a lot of encouragement and some messages that people would buy this (functional) computer model. So, here we are. The first steps have been taken, and it is time to gather potential buyers. If you like this project and are interested in buying your own personal NeXTcube mini, MegaPixel Display or SoundBox on a scale of 1:2, please sign up. You will be kept up to date on the project and will receive information as soon as sales begin. Btw: If you like, you can follow the current design process in this live rendering . Here you can see which parts the model consists of and which parts are currently available (not all are sold)."
      ],
      "headings": [],
      "tags": [
        {
          "name": "3DPrint",
          "slug": "3dprint"
        },
        {
          "name": "Electronics",
          "slug": "electronics"
        },
        {
          "name": "NeXT",
          "slug": "next"
        }
      ],
      "image": "../assets/img/NeXTcube-mini.jpg"
    },
    {
      "id": 18,
      "title": "PandaDock: Tiltable Panda Touch Dock",
      "slug": "pandadock",
      "kind": "page",
      "status": "public",
      "featured": false,
      "language": "en",
      "translationOf": null,
      "date": 1729704000000,
      "readTime": 5,
      "excerpt": "This is the detailed assembly documentation for the PandaDock - The Tiltable Panda Touch Dock . You will find the model @MakerWorld .",
      "paragraphs": [
        "This is the detailed assembly documentation for the PandaDock - The Tiltable Panda Touch Dock . You will find the model @MakerWorld .",
        "The Bambu Lab P1S (and the P1P, too) is a great 3D printer. Unfortunately, it has a very poor display. There are a few projects that aim to improve this, such as the open-source project xtouch or BigTreeTech's Panda Touch . This model is about the latter. BigTreeTech offers a display for Bambu Lab printers, which provides pretty much the same interface as an X1C. But it can do more. The Panda Touch can also operate several printers simultaneously, up to 10. Included is a very rudimentary dock that is supposed to be stuck on top of the printer, over the original display. I didn't like that. I wanted a version that worked similarly to the display on the X1C. It should be able to be swiveled. And the model I am offering here does exactly that.",
        "The picture shows all the parts needed for this dock (unfortunately I forgot to add the two self locking nuts).",
        "First, you need to remove the original display from your P1S/P1P. To do this, simply push it to the right (it may be a bit hard to move). Then you can easily move it away from the printer.",
        "Now remove the plug from the back of the display. Next you should prepare the USB-A to USB-C charging cable (as mentioned in the bill of material, a cable with only two wires for 5V and GND is good). Cut the cable at the USB-A end about 5-10cm from the plug. Depending on how long your cable is, you may need to trim the other part. Overall, a length of about 30cm should be sufficient.",
        "Then take the Dock Base, feed the display cable from the printer through the back and screw it to the printer with two M3x10 socket head screws. Now pass the part with the USB-C plug through the front of the printer (where the cable for the display comes out) and slide it to the right until it comes out again on the inside near the USB-A socket. The two pieces of cable must now be soldered together again.",
        "Important: Don't forget to pull the heat-shrink tubing over the wires and the cable beforehand!"
      ],
      "headings": [
        "The Idea",
        "Bill of Material",
        "The Components",
        "The Assembly"
      ],
      "tags": [],
      "image": "../assets/img/banner-pandadock.jpg"
    },
    {
      "id": 20,
      "title": "Touch Magic: Custom Apple Touch ID",
      "slug": "touch-magic",
      "kind": "page",
      "status": "public",
      "featured": false,
      "language": "en",
      "translationOf": null,
      "date": 1716802680000,
      "readTime": 2,
      "excerpt": "Quite a while ago, I stumbled across this project online that immediately caught my attention. Its claim was:",
      "paragraphs": [
        "Quite a while ago, I stumbled across this project online that immediately caught my attention. Its claim was:",
        "Cool! I wanted something like that too. Touch ID on every Apple Silicon Mac with every keyboard, that sounds very tempting. I read the documentation, watched his video and some of the remixes of his model. One remix really impressed me. It was the little things like \"centered Touch ID button\", \"clickable button\" etc. that I liked. So I designed my version with Shapr3D .",
        "Okay, my mind was made up. I'm going to create a remix of this remix. 😃 The main difference in my version is the integration of the Lightning connector and a simplification of the Touch ID button integration. The Lightning connector should not be fixed to the case, but mounted separately on its own adapter. However, first things first. What do we need to build our own \"Touch Magic\"?",
        "I recommend buying a keyboard on ebay or another platform. Look for devices that are labelled as defective or spare parts donors. Only the Touch ID sensor needs to work. Everything else is irrelevant.",
        "The video from SnazzyLabs , whose model on Printables inspired me, was a great help, especially on opening up the defective keyboard. It is definitely very helpful to avoid destroying it. So, take your time, watch the video and if you're unsure have a look on KhaosT's guide on how to disassemble the keyboard.",
        "After many hours of testing and customising Calvin's remix, I discarded the idea and completely redesigned the case based on his design. A bazillion test prints later, it was ready. This is what it should look like .",
        "Well, and this is it. It only needs 5 parts to be printed. No glue, no tape and less screws than the other models. AND: The button is still clickable."
      ],
      "headings": [
        "The Model",
        "The Result",
        "Notes"
      ],
      "tags": [],
      "image": "../assets/img/banner-touch-magic.jpg"
    },
    {
      "id": 16,
      "title": "Gimli: Der Kleine aus Bambus",
      "slug": "gimli",
      "kind": "page",
      "status": "public",
      "featured": false,
      "language": "de",
      "translationOf": null,
      "date": 1694440140000,
      "readTime": 2,
      "excerpt": "Irgendwann beschloss ich, dass ich auf meinem Schreibtisch neben meinem iMac auch zwei schöne aber selbstgebaute Lautsprecher stehen haben möchte. Also begann ich zu planen… Es war schon…",
      "paragraphs": [
        "Irgendwann beschloss ich, dass ich auf meinem Schreibtisch neben meinem iMac auch zwei schöne aber selbstgebaute Lautsprecher stehen haben möchte. Also begann ich zu planen… Es war schon eine ganze Weile her (fast ein ganzes Jahr), dass ich im örtlichen Baumarkt einige Bambusplatten gekauft hatte. Mein Plan war es von Anfang an, daraus Lautsprecher zu bauen. Und so standen sie erstmal eine ganze Weile herum. Aber jetzt entstand mein erstes eigenes Paar Lautsprecher, und ich nenne sie: Gimli Ich war schon sehr neugierig auf die Arbeit mit diesem Material, da es sich etwas von Massivholz oder dem üblichen Plattenmaterial Multiplex oder Sperrholz unterscheidet. Denn Bambus ist eigentlich gar kein Holz, sondern ein Gras.",
        "Okay, bevor ein Projekt zum Leben erweckt wird, gibt es einen Plan. Ich verwende dafür entweder SketchUp , Fusion 360 oder neuerdings auch Shapr3D . Für dieses Projekt habe ich mich für SketchUp entschieden, weil... nun ja... 🤷 Und das sind die Entwürfe.",
        "Wie sich (für mich) schnell herausstellte, ist Bambus in der Verarbeitung etwas anders als \"echtes\" Holz. Da es sehr faserig ist, muss man beim Sägen darauf achten, das richtige Sägeblatt zu verwenden, sonst fängt es sehr schnell an zu splittern. Aber nach ein paar Versuchen und Fehlschlägen habe ich es hinbekommen. Wie man auf den Bildern unten sehen kann, ist nicht Alles wirklich perfekt geworden. Aus irgendeinem Grund sind die Rückwände zu klein geraten. Natürlich habe ich das erst bemerkt, nachdem ich alle Löcher gebohrt und die Oberfläche geschliffen hatte. Nun, ich hab sie dann einfach nochmal neu gebaut. 🙄",
        "Damit auch der Bass bei einem so kleinen Lautsprecher einigermaßen gut hörbar ist, ist ein Bassreflex-Design sinnvoll. Und dafür braucht man ein Bassreflex-Rohr. Für die Größe dieses Lautsprechers brauchte ich ein Rohr von 9cm Länge und 3cm Innendurchmesser. Ich habe es selbst mit Shapr3D entworfen und mit meinem Ender 3 v2 ausgedruckt.",
        "Und hier sind sie. Ich finde, sie sehen wirklich hübsch aus. Ich muss sie noch eine Weile testen. Was ich jetzt schon sagen kann, sie klingen ziemlich gut für ihre Größe. Diese kleinen Breitband-Woofer von Tang Band ( W3-881SJF ) können richtig tief gehen - wenn sie im richtigen Gehäuse wohnen. Gimli hat ein Volumen von 3 Litern und, wie oben schon erwähnt, ein Bassreflexrohr auf der Rückseite."
      ],
      "headings": [],
      "tags": [],
      "image": "../assets/img/img_0528-2.jpg"
    },
    {
      "id": 14,
      "title": "Swift: Don't use nested ternary operators",
      "slug": "swift-dont-use-nested-ternary-operators",
      "kind": "post",
      "status": "public",
      "featured": false,
      "language": "en",
      "translationOf": null,
      "date": 1686527340000,
      "readTime": 3,
      "excerpt": "The ternary operator is a very handy notation to simply abbreviate if else constructs. And often it’s seen nested - one, two or three times. The compiler has no problems with such code. But…",
      "paragraphs": [
        "The ternary operator is a very handy notation to simply abbreviate if else constructs. And often it’s seen nested - one, two or three times. The compiler has no problems with such code. But we, as human beings, reach the limits. Martin Fowler , a British-American software developer, author and international speaker on the subject of software architecture, said about code readability:",
        "Now a variable is to be assigned a value, depending on the 3 conditions c1 , c2 and c3 . The simplest approach could be:",
        "This code is absolutely correct and both the compiler and every developer can understand it with a blink of an eye. But using such code can be a bit tricky if you want to apply it in a SwiftUI view modifier, for example to set a color or font of a Text view. In such a case, one tends to use a so-called ternary operator, the short form of if else in one line.",
        "This code is also absolutely correct and returns the same result as the if else construct above. But honestly, we don’t need to discuss readability here. We can of course use if else to directly assign the value to our result variable. It would look like this:",
        "As of Swift 5.9 you can get rid of the needed closure, which results in code looking like this:",
        "But in my opinion it still isn’t good to read. What I want is nearly “plain english”. Just as if I were reading a sentence. So I came to a very simple solution which is nothing else as syntactic sugar. But in my opinion very tasty sugar when it comes to read that code. Instead of using (nested) ternary operators we define one simple function:"
      ],
      "headings": [],
      "tags": [
        {
          "name": "Software",
          "slug": "software"
        },
        {
          "name": "Swift",
          "slug": "swift"
        }
      ],
      "image": "../assets/img/Hero-Swift-2xl-2.jpg"
    },
    {
      "id": 19,
      "title": "Mastodon: A new Love",
      "slug": "mastodon-a-new-love",
      "kind": "post",
      "status": "public",
      "featured": false,
      "language": "en",
      "translationOf": null,
      "date": 1654414860000,
      "readTime": 2,
      "excerpt": "I became part of the Fediverse over four years ago, but it’s only been in the last year or so that I’ve really grown to love it and use it almost daily. In 2009, I became part of Twitter.…",
      "paragraphs": [
        "I became part of the Fediverse over four years ago, but it’s only been in the last year or so that I’ve really grown to love it and use it almost daily. In 2009, I became part of Twitter. Sometime in June, I finally managed to click my way into an account. I have to admit, I didn't really understood this new medium at the time. And it took a few weeks until it worked for me. And from that moment on it turned into an addiction. Without any idea from where this special feeling came from, I suffered from FOMO after several days of abstinence. But it was great. Everything was still fresh and the stories were pouring in. I was one of the first to notice \" Collateral Murder \". Simply because it made the rounds there first. In general, I remember that year (2010) as a \"Wikileaks year\". Twitter has been the source of almost every project I've been involved with in my 8 years of freelancing. I basically didn't have to do anything more than to broadcast that I was looking. The projects came to me. I made a lot of contacts, mainly in the professional environment. But over the years, the mood there has gradually changed. More and more \"neckties\" as well as marketing and advertising buzzards pitched up here, spread their legs and \"claimed turf\". The tone became rougher and... well, you know that. Then, four years ago, Mastodon came to my attention. My first reaction: \"What a stupid name is that?\"",
        "Well-functioning mobile and desktop clients were still very thin on the ground, and frankly, non-existent. The interface felt a bit weird to me as a die-hard Twitter junkie initially. But I liked it here. So I stayed. And today I read a toot from @DerWagrier where he wrote something about groups on Mastodon (German) that you can follow. What a great thing! I had never heard of it before.",
        "I like the idea so much (many greetings to the unknown developer), so I also created a new group myself with the name @Swift . As it should be, this is all about Swift/SwiftUI development. At the time of writing this article, I seem to be the only follower. But it's not like I'm inexperienced when it comes to talking to myself... 😂 Mastodon is something of a feel-good place for me at the moment. I really hope it will stay that way for a very long time. But the fact that it's not a profit-oriented company, but a federated network driven by private individuals, seems to strongly support all of that. 🤞🏼🤞🏼🤞🏼"
      ],
      "headings": [],
      "tags": [
        {
          "name": "Fediverse",
          "slug": "fediverse"
        },
        {
          "name": "Mastodon",
          "slug": "mastodon"
        }
      ],
      "image": "../assets/img/banner-mastodon.jpg"
    },
    {
      "id": 15,
      "title": "SwiftUI: Platform ViewModifier",
      "slug": "swiftui-platform-viewmodifier",
      "kind": "post",
      "status": "public",
      "featured": false,
      "language": "en",
      "translationOf": null,
      "date": 1654260900000,
      "readTime": 2,
      "excerpt": "SwiftUI is fantastic when you need to write code for different platforms. The code can be shared. But how do I distinguish platform-specific code parts? In my employer's current project,…",
      "paragraphs": [
        "SwiftUI is fantastic when you need to write code for different platforms. The code can be shared. But how do I distinguish platform-specific code parts? In my employer's current project, SwiftUI is sometimes pushed to the limits of what is still \"elegantly feasible\". You realize that it is still a work in progress, where Apple has a lot of bugs to fix or missing features to add. Our project is being developed for iOS (both iPads and iPhones) as well as macOS. Swift in general, and SwiftUI in particular makes it really easy for us to have a common code base for everything. But every now and then, platform-specific code needs to be written. The distinction for this is made by so-called preprocessor macros. It looks something like this:",
        "But as the code base grows, so does the number of these not-so-pretty code switches. So I had the idea to hide the whole thing in a ViewModifier. The preprocessor switches do not disappear completely, but they can be reduced quite nicely. My first attempt looked like this:",
        "I posted this on Twitter, and it immediately triggered a constructive thread. There was a lot of agreement and also suggestions for improvement. 🤓 The result finally looks like this:",
        "Of course, you can find the whole thing in a Gist on GitHub . What do you think? Useful or syntactic sugar?"
      ],
      "headings": [],
      "tags": [
        {
          "name": "Software",
          "slug": "software"
        },
        {
          "name": "Swift",
          "slug": "swift"
        },
        {
          "name": "SwiftUI",
          "slug": "swiftui"
        }
      ],
      "image": "../assets/img/Hero-Swift-2xl-2.jpg"
    }
  ],
  "tags": [
    {
      "name": "3DPrint",
      "slug": "3dprint"
    },
    {
      "name": "BSD",
      "slug": "bsd"
    },
    {
      "name": "CSS",
      "slug": "css"
    },
    {
      "name": "Editor",
      "slug": "editor"
    },
    {
      "name": "Electronics",
      "slug": "electronics"
    },
    {
      "name": "Emulator",
      "slug": "emulator"
    },
    {
      "name": "Fediverse",
      "slug": "fediverse"
    },
    {
      "name": "General",
      "slug": "general"
    },
    {
      "name": "Javascript",
      "slug": "javascript"
    },
    {
      "name": "Linux",
      "slug": "linux"
    },
    {
      "name": "Mastodon",
      "slug": "mastodon"
    },
    {
      "name": "NeXT",
      "slug": "next"
    },
    {
      "name": "NeXTSTEP",
      "slug": "nextstep"
    },
    {
      "name": "Operating System",
      "slug": "operating-system"
    },
    {
      "name": "Previous",
      "slug": "previous"
    },
    {
      "name": "RaspberryPi",
      "slug": "raspberrypi"
    },
    {
      "name": "Software",
      "slug": "software"
    },
    {
      "name": "Swift",
      "slug": "swift"
    },
    {
      "name": "SwiftUI",
      "slug": "swiftui"
    },
    {
      "name": "Text Editor",
      "slug": "text-editor"
    },
    {
      "name": "Web-Development",
      "slug": "web-development"
    },
    {
      "name": "nano",
      "slug": "nano"
    },
    {
      "name": "vi",
      "slug": "vi"
    }
  ]
};
