// The dashboard is built to static files and served by nginx, so its build is a
// build rather than a bundle for now. Vite replaces this with its own output
// when the shell epic lands; what matters here is that `dist/` exists, holds an
// index, and carries the nginx configuration that puts the headers on it.
import { mkdir, writeFile } from "node:fs/promises";
import { dashboardPolicy, NO_FRAMING, SHARED_HEADERS } from "@layered/policy";

/** Where the API answers. The dashboard talks to nothing else. */
const API_ORIGIN = process.env.API_ORIGIN ?? "https://api.layered.work";

const dist = new URL("./dist/", import.meta.url);
await mkdir(dist, { recursive: true });

await writeFile(
  new URL("./index.html", dist),
  `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="robots" content="noindex" />
    <title>layered.work dashboard</title>
  </head>
  <body>
    <h1>Dashboard</h1>
    <p>Not built yet. This page proves the static path: built here, served by nginx.</p>
  </body>
</html>
`,
);

/**
 * nginx serves this host, so nginx is what puts the headers on it.
 *
 * Generated rather than written by hand, from the same definitions the other
 * two surfaces read. A configuration file looks like data and is therefore
 * copied more readily than code, and a copy of a security header is the kind
 * that disagrees silently.
 *
 * `always` on each one, because without it nginx omits the header on an error
 * response, and an error page is a document like any other.
 */
const headers = { ...SHARED_HEADERS, ...NO_FRAMING, "Content-Security-Policy": dashboardPolicy(API_ORIGIN) };

await writeFile(
  new URL("./site.conf", dist),
  `# Generated by apps/dashboard/build.mjs from @layered/policy. Do not edit.
server {
    listen 80;
    server_name _;
    root /var/www/apps/dashboard/dist;
    index index.html;

${Object.entries(headers)
  .map(([name, value]) => `    add_header ${name} "${value}" always;`)
  .join("\n")}

    # A single-page interface: every address that is not a file is the shell,
    # and the shell decides what to show. Without this a reload on any screen
    # other than the first answers 404.
    location / {
        try_files $uri $uri/ /index.html;
    }
}
`,
);

console.log("dashboard: dist/index.html and dist/site.conf written");
