import { existsSync } from "node:fs";
import { readFile, realpath, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { dashboardPolicy, NO_FRAMING, SHARED_HEADERS } from "@layered/policy";
import { ErrorCode } from "@layered/schemas";
import { copyUiAssets } from "@layered/ui/copy-assets";

/** Retain the licence texts of runtime dependencies, including bundled transitives. */
async function dependencyNotices() {
  const seen = new Set();
  const notices = [];
  async function visit(manifestPath) {
    const manifestFile = await realpath(manifestPath);
    const manifest = JSON.parse(await readFile(manifestFile, "utf8"));
    const identity = `${manifest.name}@${manifest.version}`;
    if (seen.has(identity)) return;
    seen.add(identity);
    if (!manifest.private) {
      const directory = dirname(manifestFile);
      const licence = ["LICENSE", "LICENSE.md", "LICENSE.txt", "license", "license.md"]
        .map((name) => join(directory, name))
        .find(existsSync);
      if (!licence) throw new Error(`Missing licence text for ${identity}`);
      notices.push(`${identity}\n${await readFile(licence, "utf8")}`);
    }
    const require = createRequire(manifestFile);
    await Promise.all(
      Object.keys(manifest.dependencies ?? {}).map(async (name) => {
        const dependency = require.resolve
          .paths(name)
          ?.map((directory) => join(directory, name, "package.json"))
          .find(existsSync);
        if (!dependency) throw new Error(`Cannot locate the licence package for ${name}`);
        await visit(dependency);
      }),
    );
  }
  await visit(new URL("./package.json", import.meta.url));
  return notices.sort().join("\n\n");
}

/** nginx 1.22 inherits headers only when a location declares none of its own. */
function nginxHeaders(headers, indent = "    ") {
  return Object.entries(headers)
    .map(([name, value]) => `${indent}add_header ${name} "${value}" always;`)
    .join("\n");
}

/** Prepare nginx and shared public assets after Vite has emitted the application. */
export async function prepareDeployment(dist, apiOrigin) {
  await copyUiAssets(dist);
  await writeFile(new URL("./DEPENDENCY_LICENSES.txt", dist), await dependencyNotices());
  const headers = { ...SHARED_HEADERS, ...NO_FRAMING, "Content-Security-Policy": dashboardPolicy() };
  await writeFile(
    new URL("./site.conf", dist),
    `# Generated by apps/dashboard/deploy.mjs. Do not edit.
# Only proxy-generated failures use this log; no query, cookie or body is logged.
log_format dashboard_api_failure escape=json '{"code":"internal","errorId":"$request_id","requestId":"$request_id","route":"$uri","status":$status,"result":"upstream_unavailable","upstreamStatus":"$upstream_status"}';

server {
    listen 80;
    server_name _;
    root /var/www/apps/dashboard/dist;
    index index.html;

${nginxHeaders(headers)}

    # Same-origin cookies stay on the dashboard host; the private upstream
    # receives the existing edge chain unchanged, preserving per-client limits.
    location /api/ {
        proxy_pass ${apiOrigin}/;
        proxy_set_header Host $proxy_host;
        proxy_set_header X-Forwarded-For $http_x_forwarded_for;
        proxy_intercept_errors off;
        proxy_cache off;
${
  apiOrigin.startsWith("https:")
    ? `        proxy_ssl_server_name on;
        proxy_ssl_verify on;
        proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
`
    : ""
}        error_page 502 503 504 = @api_unavailable;
    }

    location @api_unavailable {
        access_log syslog:server=unix:/dev/log,facility=local1,tag=nginx,severity=error dashboard_api_failure;
        default_type application/json;
${nginxHeaders(headers, "        ")}
        add_header Cache-Control "no-store" always;
        add_header X-Request-ID $request_id always;
        return 502 '{"error":{"code":"${ErrorCode.Internal}","message":"The API is temporarily unavailable.","id":"$request_id"}}';
    }

    # Missing bundles must not answer with the SPA document.
    location /assets/ {
        try_files $uri =404;
    }

    # Data-router routes survive direct navigation and browser reloads.
    location / {
        try_files $uri $uri/ /index.html;
    }
}
`,
  );
}
