import { existsSync } from "node:fs";
import { readFile, realpath, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { dashboardPolicy, NO_FRAMING, SHARED_HEADERS } from "@layered/policy";
import { copyUiAssets } from "@layered/ui/copy-assets";

/** Retain the licence texts of runtime dependencies, including bundled transitives. */
async function dependencyNotices() {
  const seen = new Set();
  const notices = [];
  async function visit(manifestPath) {
    const manifestFile = await realpath(manifestPath);
    const manifest = JSON.parse(await readFile(manifestFile, "utf8"));
    const identity = `${manifest.name}@${manifest.version}`;
    if (seen.has(identity)) return;
    seen.add(identity);
    if (!manifest.private) {
      const directory = dirname(manifestFile);
      const licence = ["LICENSE", "LICENSE.md", "LICENSE.txt", "license", "license.md"]
        .map((name) => join(directory, name))
        .find(existsSync);
      if (!licence) throw new Error(`Missing licence text for ${identity}`);
      notices.push(`${identity}\n${await readFile(licence, "utf8")}`);
    }
    const require = createRequire(manifestFile);
    await Promise.all(
      Object.keys(manifest.dependencies ?? {}).map(async (name) => {
        const dependency = require.resolve
          .paths(name)
          ?.map((directory) => join(directory, name, "package.json"))
          .find(existsSync);
        if (!dependency) throw new Error(`Cannot locate the licence package for ${name}`);
        await visit(dependency);
      }),
    );
  }
  await visit(new URL("./package.json", import.meta.url));
  return notices.sort().join("\n\n");
}

/** Prepare nginx and shared public assets after Vite has emitted the application. */
export async function prepareDeployment(dist, apiOrigin) {
  await copyUiAssets(dist);
  await writeFile(new URL("./DEPENDENCY_LICENSES.txt", dist), await dependencyNotices());
  const headers = { ...SHARED_HEADERS, ...NO_FRAMING, "Content-Security-Policy": dashboardPolicy(apiOrigin) };
  await writeFile(
    new URL("./site.conf", dist),
    `# Generated by apps/dashboard/deploy.mjs. Do not edit.
server {
    listen 80;
    server_name _;
    root /var/www/apps/dashboard/dist;
    index index.html;

${Object.entries(headers)
  .map(([name, value]) => `    add_header ${name} "${value}" always;`)
  .join("\n")}

    # Missing bundles must not answer with the SPA document.
    location /assets/ {
        try_files $uri =404;
    }

    # Data-router routes survive direct navigation and browser reloads.
    location / {
        try_files $uri $uri/ /index.html;
    }
}
`,
  );
}
